In [1]:
import torch
import numpy as np 
import matplotlib.pyplot as plt

In [9]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,
                        device="cuda",requires_grad=True)

In [10]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [11]:
my_tensor.dtype,my_tensor.device,my_tensor.shape

(torch.float32, device(type='cuda', index=0), torch.Size([2, 3]))

In [12]:
my_tensor.requires_grad

True

In [15]:
x = torch.empty(size=(3,3))
x = torch.zeros((3,3))
x = torch.ones((3,3))
x = torch.rand((3,3))
x = torch.eye(5,5)
print(x)
x = torch.arange(start=0,end=5,step=1)
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [17]:
x = torch.diag(torch.rand(3))
x

tensor([[0.9191, 0.0000, 0.0000],
        [0.0000, 0.9410, 0.0000],
        [0.0000, 0.0000, 0.5191]])

In [21]:
np_array = np.random.randint(5,10,size=(5,5))
np_array

array([[5, 7, 9, 6, 7],
       [9, 6, 9, 9, 6],
       [7, 8, 8, 6, 9],
       [5, 6, 5, 9, 7],
       [5, 8, 9, 7, 7]])

In [23]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[5, 7, 9, 6, 7],
        [9, 6, 9, 9, 6],
        [7, 8, 8, 6, 9],
        [5, 6, 5, 9, 7],
        [5, 8, 9, 7, 7]])

In [24]:
np_array_back = tensor.numpy()

# Math operation

In [25]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])

z = torch.empty(3)
torch.add(x,y,out=z)
z

tensor([2., 4., 6.])

In [26]:
x = torch.rand(5,5)

In [27]:
x

tensor([[0.0458, 0.7477, 0.1527, 0.9496, 0.7865],
        [0.8646, 0.9456, 0.3072, 0.4402, 0.5912],
        [0.7576, 0.3860, 0.4652, 0.8862, 0.1983],
        [0.1747, 0.9077, 0.0224, 0.3490, 0.7803],
        [0.6921, 0.9368, 0.8767, 0.3820, 0.1019]])

In [30]:
x = x.pow(2)
x = x ** 2

In [29]:
x

tensor([[2.1005e-03, 5.5908e-01, 2.3313e-02, 9.0182e-01, 6.1860e-01],
        [7.4755e-01, 8.9407e-01, 9.4364e-02, 1.9380e-01, 3.4950e-01],
        [5.7389e-01, 1.4898e-01, 2.1644e-01, 7.8529e-01, 3.9304e-02],
        [3.0529e-02, 8.2397e-01, 5.0312e-04, 1.2183e-01, 6.0887e-01],
        [4.7901e-01, 8.7753e-01, 7.6866e-01, 1.4593e-01, 1.0376e-02]])

In [35]:
x > 0.5

tensor([[False, False, False,  True, False],
        [False,  True, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True, False, False, False]])

In [36]:
x[x > 0.5]

tensor([0.6614, 0.6390, 0.5930])

In [45]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,2,3],[4,5,6]])                  
z = x * y
print(z)
z = x.mm(y.T)
print(z)

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[14, 32],
        [32, 77]])


In [43]:
z = torch.dot(x.flatten(),y.flatten())
z

tensor(91)

In [46]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand(batch,n,m)
tensor2 = torch.rand(batch,m,p)
out = tensor1.bmm(tensor2) # batch matrix multiplication output (batch,n,p)

In [47]:
out.shape

torch.Size([32, 10, 30])

In [51]:
# useful tensor operations
sum_x = torch.sum(x,dim=0) # COL index
print(sum_x)

tensor([5, 7, 9])


In [52]:
values,indices = torch.max(x,dim=0)
print(values,indices)

tensor([4, 5, 6]) tensor([1, 1, 1])


In [53]:
# absolute value
abs_x = torch.abs(x)
abs_x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [56]:
z = torch.argmax(x,dim=1)
z = torch.argmin(x,dim=0)
z

tensor([0, 0, 0])

In [57]:
z = torch.eq(x,y)
z

tensor([[True, True, True],
        [True, True, True]])

In [60]:
z = torch.clamp(x,min=3,max=5)
z

tensor([[3, 3, 3],
        [4, 5, 5]])

In [61]:
tensor = torch.tensor([1,0,1,1],dtype=torch.bool)
tensor

tensor([ True, False,  True,  True])

In [62]:
torch.any(tensor)

tensor(True)

In [63]:
torch.all(tensor)

tensor(False)

In [65]:
tensor[tensor > 0] = 0
tensor

tensor([False, False, False, False])

# Tensor Indexing

In [67]:
batch_size = 32
features = 15
x = torch.rand(batch_size,features)


In [69]:
# first feature
print(x[0].shape)
print(x[:,0].shape)

torch.Size([15])
torch.Size([32])


In [71]:
# third 10 freautres
print(x[2,0:10].shape)

torch.Size([10])


In [74]:
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,2])
cols = torch.tensor([3,1])
x[rows,cols]

tensor([[0.1850, 0.0113, 0.6555, 0.3036, 0.2490],
        [0.5267, 0.8078, 0.2541, 0.1931, 0.0918],
        [0.5655, 0.4089, 0.5143, 0.8291, 0.4744]])


tensor([0.1931, 0.4089])

In [75]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [76]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [78]:
print(torch.where(x > 5,x,torch.tensor(1)))

tensor([1, 1, 1, 1, 1, 1, 6, 7, 8, 9])


In [79]:
print(torch.tensor([0,0,0,1,1,1,2,2,3]).unique())

tensor([0, 1, 2, 3])


In [80]:
print(x.ndimension())

1


In [81]:
print(x.numel())

10


# Reshpaing Tensor

In [82]:
x = torch.arange(9)
x_3x3 = x.view(3,3)

In [83]:
x_3x3 = x.reshape(3,3)

In [86]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)

torch.Size([4, 5])


In [87]:
z = x.view(-1)
print(z.shape)

torch.Size([9])


In [89]:
batch = 64
x = torch.rand(batch,2,5)
z = x.view(batch,-1)
print(z.shape)

torch.Size([64, 10])


In [91]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [93]:
# add another dimension
x = torch.arange(10)
print(x.shape)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])


In [94]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
x.shape

torch.Size([1, 1, 10])

In [98]:
print(x.squeeze(0).shape)

torch.Size([1, 10])
